CC=g++
CFLAGS=-std=c++17 -O3 -Wall -Werror
TESTFLAGS=-lgtest -pthread

any:
	$(CC) any.cpp -o any.out $(CFLAGS)

are_same:
	$(CC) are_same.cpp -o are_same.out $(CFLAGS)

exc:
	$(CC) exc.cpp -o exc.out $(CFLAGS) $(TESTFLAGS)